### ISSUE TITLE
Task not working

### ISSUE THREAD

**Issue by reintroducing** [straker/gulp-livingcss#2]
Hello,
I'm trying to implement this task in its simplest form and I'm getting the following error:

```
[16:03:58] Starting 'livingcss'...
[16:03:58] 'livingcss' errored after 10 ms
[16:03:58] TypeError: Cannot read property 'on' of undefined
    at DestroyableTransform.Readable.pipe (/Users/przybylski/retrofit/dev/code/client-dashboard/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:516:7)
    at Gulp.<anonymous> (livingcss.js:7:10)
    at module.exports (/Users/przybylski/retrofit/dev/code/client-dashboard/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/przybylski/retrofit/dev/code/client-dashboard/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/przybylski/retrofit/dev/code/client-dashboard/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/przybylski/retrofit/dev/code/client-dashboard/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/przybylski/retrofit/dev/code/client-dashboard/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

My task is as follows:

```
import gulp from 'gulp';
import livingcss from 'livingcss';
import config from '../../config.json';

gulp.task('livingcss', () => {
    gulp.src(`${config.sass.path}/**/*.scss`)
        .pipe(livingcss())
        .pipe(gulp.dest(config.css.path));
});
```

There is really only one file thus far with LivingCSS comments in it in that path (although multiple files exist).  Any ideas on what I may be doing wrong?  

I know the paths are correct because these are the same exact paths that my sass task uses to generate the output css.

Appreciate any help offered.

**Comment by straker** [comment]
Just to double check, but did you install `gulp-livingcss` or `livingcss`? The way your import is set up it looks like you just got `livingcss`.

**Comment by reintroducing** [comment]
Yep, you're absolutely right, a total miss on my part. I originally started off using livingcss and then realized there was a gulp task so moved to it and forgot to change the import. My apologies and cheers for the keen eye.
